name: Copy project files to server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: Test SSH connection
        run: |
          ssh -v -i /home/runner/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "echo SSH connection test successful"
      - name: Copy project files to server
        run: |
          echo "Listing files in GitHub Actions runner before rsync:"
          ls -la
          echo "SSH_USER: ${{ secrets.SSH_USER }}"
          echo "SERVER_IP: ${{ secrets.SERVER_IP }}"
          echo "DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}"
          rsync -avzr -e "ssh -i /home/runner/.ssh/id_ed25519" --exclude '__pycache__' --exclude '.git' --exclude '.gitignore' --exclude '.env_sample' ./ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_DIR }}